name: APIs.json
description: The open source API discovery format.
image: https://kinlane-productions2.s3.amazonaws.com/apis-json/apis-json-logo.jpg
url: https://apisjson.org

node: explore

keywords:

  - APIs
  - Search
  - Discovery

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

categories_path : /categories.html
tags_path : /tags.html

github_org: apis-json
github_repo: apis-json-website

search_local: true

collections:
  common:
    output: true
    permalink: /common/:path/    

defaults:

  - scope:
      path:         ""
      type:         common
    values:
      layout:       common
